# Use an official Ruby image as a parent image
FROM ruby:2.7

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the Gemfile and Gemfile.lock into the container
COPY Gemfile Gemfile.lock ./

# Not sure why we need to do this on Google Cloud
RUN gem install bundler -v '1.14.6'

# Install any needed gems specified in Gemfile
RUN bundle install

# Copy the rest of your app's source code from your host to your container
COPY . .

# Add metadata to the image to describe which port the container is listening on at runtime
EXPOSE 3000

# Precompile assets
# Set RAILS_ENV and SECRET_KEY_BASE as these might be required for asset compilation
ENV RAILS_ENV=production SECRET_KEY_BASE=temporary_key
RUN rails assets:precompile

# Start the main process
CMD ["rails", "runner", "Shelter.update_all"]
